// GENERATED by sigla-ml/tools/gen_tap_clip_fixtures.py — do not edit by hand.
// Regenerating to make ClipPreparerParityTest pass is wrong: see the generator.
package com.example.sigla

internal class TapSampleCase(val totalFrames: Int, val sourceFps: Double, val expected: IntArray)

internal class TapFinalizeCase(
    val name: String, val pattern: String, val slope: Double, val peakAt: Int,
    val jump: Double, val totalFrames: Int, val sourceFps: Double,
    val expectedReason: String?, val expectedFrameSums: FloatArray?,
)

internal val TAP_SAMPLE_CASES = listOf(
    TapSampleCase(45, 24.0, intArrayOf(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44)),
    TapSampleCase(60, 30.0, intArrayOf(0, 1, 2, 3, 5, 6, 7, 8, 10, 11, 12, 13, 15, 16, 17, 18, 20, 21, 22, 23, 25, 26, 27, 28, 30, 31, 32, 33, 35, 36, 37, 38, 40, 41, 42, 43, 45, 46, 47, 48, 50, 51, 52, 53, 55, 56, 57, 58)),
    TapSampleCase(90, 30.0, intArrayOf(0, 1, 2, 3, 5, 6, 7, 8, 10, 11, 12, 13, 15, 16, 17, 18, 20, 21, 22, 23, 25, 26, 27, 28, 30, 31, 32, 33, 35, 36, 37, 38, 40, 41, 42, 43, 45, 46, 47, 48, 50, 51, 52, 53, 55, 56, 57, 58, 60, 61, 62, 63, 65, 66, 67, 68, 70, 71, 72, 73, 75, 76, 77, 78, 80, 81, 82, 83, 85, 86, 87, 88)),
    TapSampleCase(200, 30.0, intArrayOf(0, 2, 4, 7, 9, 11, 14, 16, 18, 21, 23, 25, 28, 30, 32, 35, 37, 39, 42, 44, 46, 49, 51, 53, 56, 58, 60, 63, 65, 67, 70, 72, 74, 77, 79, 81, 84, 86, 88, 91, 93, 95, 98, 100, 103, 105, 107, 110, 112, 114, 117, 119, 121, 124, 126, 128, 131, 133, 135, 138, 140, 142, 145, 147, 149, 152, 154, 156, 159, 161, 163, 166, 168, 170, 173, 175, 177, 180, 182, 184, 187, 189, 191, 194, 196, 199)),
    TapSampleCase(20, 30.0, intArrayOf(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19)),
    TapSampleCase(30, 60.0, intArrayOf(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29)),
    TapSampleCase(250, 60.0, intArrayOf(0, 2, 5, 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 43, 46, 49, 52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 84, 87, 90, 93, 96, 99, 102, 105, 108, 111, 114, 117, 120, 123, 125, 128, 131, 134, 137, 140, 143, 146, 149, 152, 155, 158, 161, 164, 166, 169, 172, 175, 178, 181, 184, 187, 190, 193, 196, 199, 202, 205, 207, 210, 213, 216, 219, 222, 225, 228, 231, 234, 237, 240, 243, 246, 249)),
    TapSampleCase(100, 24.0, intArrayOf(0, 1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 13, 15, 16, 17, 18, 19, 20, 22, 23, 24, 25, 26, 27, 29, 30, 31, 32, 33, 34, 36, 37, 38, 39, 40, 41, 43, 44, 45, 46, 47, 48, 50, 51, 52, 53, 54, 55, 57, 58, 59, 60, 61, 62, 64, 65, 66, 67, 68, 69, 71, 72, 73, 74, 75, 76, 78, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 90, 92, 93, 94, 95, 96, 97, 99)),
    TapSampleCase(64, 29.97, intArrayOf(0, 1, 2, 3, 4, 6, 7, 8, 9, 11, 12, 13, 14, 16, 17, 18, 19, 21, 22, 23, 24, 26, 27, 28, 29, 31, 32, 33, 34, 36, 37, 38, 39, 41, 42, 43, 44, 46, 47, 48, 49, 51, 52, 53, 54, 56, 57, 58, 59, 61, 62)),
    TapSampleCase(1, 30.0, intArrayOf(0)),
    TapSampleCase(37, 15.0, intArrayOf(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36)),
)

internal val TAP_FINALIZE_CASES = listOf(
    TapFinalizeCase("normal_45", "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH", 0.05, 22, 1.0, 45, 24.0, null, floatArrayOf(3.94099998e+01f, 4.14224998e+01f, 4.34350001e+01f, 4.54475001e+01f, 4.74600000e+01f, 4.94724997e+01f, 5.14849998e+01f, 5.34975000e+01f, 5.55100001e+01f, 5.75225001e+01f, 5.95349998e+01f, 6.15474998e+01f, 6.35600000e+01f, 6.55725000e+01f, 1.07835000e+02f, 1.09847500e+02f, 1.11860000e+02f, 1.13872500e+02f, 1.15885000e+02f, 1.17897500e+02f, 1.19910000e+02f, 1.21922500e+02f, 1.23935000e+02f, 1.25947500e+02f, 1.27960000e+02f, 1.29972500e+02f, 1.31985000e+02f, 1.33997500e+02f, 1.36010000e+02f, 1.38022500e+02f)),
    TapFinalizeCase("exact_30_stretch", "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHH", 0.05, 15, 1.0, 30, 24.0, null, floatArrayOf(3.81479243e+01f, 3.91371180e+01f, 4.01263140e+01f, 4.11155079e+01f, 4.21047039e+01f, 4.30938978e+01f, 4.40830941e+01f, 4.50722877e+01f, 4.60614837e+01f, 4.70506774e+01f, 4.80398733e+01f, 4.90290670e+01f, 5.00182631e+01f, 5.10074568e+01f, 6.22297038e+01f, 8.30027956e+01f, 9.42250430e+01f, 9.52142364e+01f, 9.62034303e+01f, 9.71926289e+01f, 9.81818227e+01f, 9.91710160e+01f, 1.00160210e+02f, 1.01149408e+02f, 1.02138602e+02f, 1.03127795e+02f, 1.04116989e+02f, 1.05106188e+02f, 1.06095382e+02f, 1.07084575e+02f)),
    TapFinalizeCase("leading_trailing", "-----HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH----", 0.05, 25, 1.0, 49, 24.0, null, floatArrayOf(4.34350001e+01f, 4.54475001e+01f, 4.74600000e+01f, 4.94724997e+01f, 5.14849998e+01f, 5.34975000e+01f, 5.55100001e+01f, 5.75225001e+01f, 5.95349998e+01f, 6.15474998e+01f, 6.35600000e+01f, 6.55725000e+01f, 6.75850001e+01f, 6.95974998e+01f, 7.16100000e+01f, 1.13872500e+02f, 1.15885000e+02f, 1.17897500e+02f, 1.19910000e+02f, 1.21922500e+02f, 1.23935000e+02f, 1.25947500e+02f, 1.27960000e+02f, 1.29972500e+02f, 1.31985000e+02f, 1.33997500e+02f, 1.36010000e+02f, 1.38022500e+02f, 1.40035000e+02f, 1.42047500e+02f)),
    TapFinalizeCase("corrupt_inside", "HHHHHHHHHHHHHHHHHHHHXXHHHHHHHHHHHHHHHHHHHH", 0.05, 21, 1.0, 42, 24.0, null, floatArrayOf(3.33725002e+01f, 3.53850001e+01f, 3.73974998e+01f, 3.94099998e+01f, 4.14224998e+01f, 4.34350001e+01f, 4.54475001e+01f, 4.74600000e+01f, 4.94724997e+01f, 5.14849998e+01f, 5.34975000e+01f, 5.55100001e+01f, 5.75225001e+01f, 5.95349998e+01f, 6.15474998e+01f, 1.07835000e+02f, 1.09847500e+02f, 1.11860000e+02f, 1.13872500e+02f, 1.15885000e+02f, 1.17897500e+02f, 1.19910000e+02f, 1.21922500e+02f, 1.23935000e+02f, 1.25947500e+02f, 1.27960000e+02f, 1.29972500e+02f, 1.31985000e+02f, 1.33997500e+02f, 1.36010000e+02f)),
    TapFinalizeCase("downsampled_long", "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH", 0.05, 35, 1.0, 88, 30.0, null, floatArrayOf(6.35600000e+01f, 6.55725000e+01f, 6.75850001e+01f, 6.95974998e+01f, 7.16100000e+01f, 7.36225000e+01f, 7.56350000e+01f, 7.76475001e+01f, 7.96599998e+01f, 8.16725000e+01f, 8.36849998e+01f, 8.56975001e+01f, 8.77100000e+01f, 8.97225000e+01f, 9.17349999e+01f, 1.33997500e+02f, 1.36010000e+02f, 1.38022500e+02f, 1.40035000e+02f, 1.42047500e+02f, 1.44060000e+02f, 1.46072500e+02f, 1.48085000e+02f, 1.50097501e+02f, 1.52110000e+02f, 1.54122500e+02f, 1.56135000e+02f, 1.58147500e+02f, 1.60160000e+02f, 1.62172501e+02f)),
    TapFinalizeCase("window_pose", "HHHHHHHHHHHHHHHhhhhhhhhhhHHHHHHHHHHHHHHH", 0.05, 20, 1.0, 40, 24.0, "window_pose", null),
    TapFinalizeCase("low_motion", "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH", 0.001, 1000000, 0.0, 45, 24.0, "low_motion", null),
    TapFinalizeCase("min_hand_frames", "HHHHHHHHHHH", 0.05, 5, 1.0, 11, 24.0, "min_hand_frames", null),
    TapFinalizeCase("hand_coverage", "HHHHHHHHHHHHHHHHHHHH------------------------------------------------------------", 0.05, 10, 1.0, 80, 24.0, "hand_coverage", null),
    TapFinalizeCase("pose_coverage", "HHHHHHHHHHHHHHHHHHHHhhhhhhhhhhhhhhhhhhhh", 0.05, 20, 1.0, 40, 24.0, "pose_coverage", null),
    TapFinalizeCase("hand_gap", "HHHHHHHHHHHHHHHHHHHH-------HHHHHHHHHHHHHHHHHHHH", 0.05, 30, 1.0, 47, 24.0, "hand_gap", null),
    TapFinalizeCase("too_short", "HHHHHHHHHHHHHHHHHHHHHHHHH", 0.05, 12, 1.0, 25, 24.0, "too_short", null),
    TapFinalizeCase("too_sparse", "H--H--H--H--H--H--H--H--H--H--H--H--H--H--H--H--H--H--H--H--H--H--H-H-H-H-H-H-H-", 0.05, 40, 1.0, 200, 30.0, "too_sparse", null),
)
