"""
Generate TapClipFixtures.kt: goldens pinning sigla-mobile's ClipPreparer to
clip_prep.sample_indices / finalize_sampled.

    venv/Scripts/python.exe tools/gen_tap_clip_fixtures.py

Inputs are NOT shipped: TapClipSynth.kt rebuilds them from each case's
parameters (see tests/_tap_clip_synth.py). Only outputs are pinned: sampled
indices, the rejection reason, or the per-frame sums of the produced window.

Regenerate ONLY after a deliberate change made on both sides. A failing
ClipPreparerParityTest means the two pipelines diverged. Fix the divergence;
do not regenerate to make it pass.
"""
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(_HERE, ".."))

from app.services.clip_prep import (  # noqa: E402
    ExtractionQualityError,
    finalize_sampled,
    sample_indices,
)
from tests._tap_clip_synth import (  # noqa: E402
    FINALIZE_CASES,
    SAMPLE_CASES,
    synth_sampled,
)

OUT = os.path.abspath(os.path.join(
    _HERE, "..", "..", "sigla-mobile", "app", "src", "test", "kotlin",
    "com", "example", "sigla", "TapClipFixtures.kt",
))


def _f(v: float) -> str:
    return f"{float(v):.8e}f"


def main() -> None:
    lines = [
        "// GENERATED by sigla-ml/tools/gen_tap_clip_fixtures.py — do not edit by hand.",
        "// Regenerating to make ClipPreparerParityTest pass is wrong: see the generator.",
        "package com.example.sigla",
        "",
        "internal class TapSampleCase(val totalFrames: Int, val sourceFps: Double, val expected: IntArray)",
        "",
        "internal class TapFinalizeCase(",
        "    val name: String, val pattern: String, val slope: Double, val peakAt: Int,",
        "    val jump: Double, val totalFrames: Int, val sourceFps: Double,",
        "    val expectedReason: String?, val expectedFrameSums: FloatArray?,",
        ")",
        "",
        "internal val TAP_SAMPLE_CASES = listOf(",
    ]
    for total, fps in SAMPLE_CASES:
        idx = ", ".join(str(int(i)) for i in sample_indices(total, fps).indices)
        lines.append(f"    TapSampleCase({total}, {fps!r}, intArrayOf({idx})),")
    lines += [")", "", "internal val TAP_FINALIZE_CASES = listOf("]
    for name, pattern, slope, peak_at, jump, total, fps, expected in FINALIZE_CASES:
        sampled = synth_sampled(pattern, slope, peak_at, jump)
        try:
            window = finalize_sampled(sampled, total, fps)
            reason, sums = None, [float(row.astype("float64").sum()) for row in window]
        except ExtractionQualityError as e:
            reason, sums = e.reason, None
        assert reason == expected, f"{name}: python gave {reason}, table says {expected}"
        reason_kt = "null" if reason is None else f'"{reason}"'
        sums_kt = "null" if sums is None else "floatArrayOf(" + ", ".join(_f(s) for s in sums) + ")"
        lines.append(
            f'    TapFinalizeCase("{name}", "{pattern}", {slope!r}, {peak_at}, {jump!r}, '
            f"{total}, {fps!r}, {reason_kt}, {sums_kt}),"
        )
    lines += [")", ""]
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
